### ISSUE TITLE
Comparison to In Context LoRA?

### ISSUE THREAD

**Issue by spacepxl** [TIGER-AI-Lab/OmniEdit#1]
https://github.com/ali-vilab/In-Context-LoRA

In theory I think IC Lora should have the same advantages from computing attention across a combined sequence of noise/image tokens, control tokens, and text tokens, but without the overhead of an added control branch. Would you consider comparing their method of image concatenation but with SD3 and your dataset?

**Comment by lim142857** [comment]
Thank you for the suggestion! However, to edit a real image using In-Context-LoRA, we would need to first perform an inversion of the image. Directly concatenating a real image with noise as input to the model wouldn’t work effectively unless the model is fine-tuned specifically for this purpose.
